[package]
name = "nabu"
version = "0.1.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]

[dependencies]
actix-web = "0.7.2"

chrono = "0.4.5"
reqwest = "0.8.6"
failure = "0.1.1"

serde = "1.0.70"
serde_derive = "1.0.70"
serde_qs = "0.4.1"
serde_json = "1.0.24"

atom_syndication = { git = "https://github.com/DCjanus/atom.git" }