version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    environment:
      PG_URL: "postgresql://nabu@db:5432/nabu"
    depends_on:
    - db

  db:
    image: "postgres:10-alpine"
    environment:
      POSTGRES_USER: "nabu"
